package cmd

import (
	"hybridctl/util"

	"github.com/aws/aws-sdk-go/service/eks"
)

// eks
var associateEncryptionConfigInput eks.AssociateEncryptionConfigInput
var associateIdentityProviderConfigInput eks.AssociateIdentityProviderConfigInput
var oidcRequest eks.OidcIdentityProviderConfigRequest
var createClusterInput util.HCPCreateClusterInput
var createNodegroupInput util.HCPCreateNodegroupInput
var createAddonInput eks.CreateAddonInput
var deleteClusterInput util.HCPDeleteClusterInput
var deleteNodegroupInput util.HCPDeleteNodegroupInput
var deleteAddonInput eks.DeleteAddonInput
var describeClusterInput util.HCPDescribeClusterInput
var describeNodegroupInput util.HCPDescribeNodegroupInput
var listClusterInput util.HCPListClusterInput
var listNodegroupInput util.HCPListNodegroupInput
var upgradeClusterInput util.HCPUpdateClusterVersionInput
var describeAddonInput eks.DescribeAddonInput
var describeAddonVersionsInput eks.DescribeAddonVersionsInput
var describeIdentityProviderConfigInput eks.DescribeIdentityProviderConfigInput
var describeUpdateInput eks.DescribeUpdateInput
var disassociateIdentityProviderConfigInput eks.DisassociateIdentityProviderConfigInput
var listAddonInput eks.ListAddonsInput
var listIdentityProviderConfigsInput eks.ListIdentityProviderConfigsInput
var listTagsForResourceInput eks.ListTagsForResourceInput
var listUpdateInput eks.ListUpdatesInput
var updateAddonInput eks.UpdateAddonInput
var updateClusterConfigInput eks.UpdateClusterConfigInput
var updateNodegroupConfigInput eks.UpdateNodegroupConfigInput
